kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-volume
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: test
          - name: MYSQL_DATABASE
            value: test
          - name: MYSQL_PASSWORD
            value: password
      volumes:
      - name: data-volume
        hostPath: 
          path: /data-volume
          type: DirectoryOrCreate
