kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PASSWORD
          value: password
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html
            name: wordpress-data
      volumes:
      - name: wordpress-data
        hostPath:
          path: /data-volume
          type: DirectoryOrCreate
