kind: Pod
apiVersion: v1
metadata:
  name: pod-blue
  namespace: production
  labels:
    app: web
spec:
  containers:
    - name: pod-blue
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: blue
