kind: Pod
apiVersion: v1
metadata:
  name: pod-red
  namespace: production
  labels:
    app: web
spec:
  containers:
    - name: pod-red
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: red
