kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: fzqvlvzvzsvavqvq
          - name: MYSQL_USER
            value: toto
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_PASSWORD
            value: toto
      volumes:
      - name: mysql-volume
        hostPath: 
          path: /data/mysql-volume
          type: DirectoryOrCreate
