kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-deployment
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-service
          - name: WORDPRESS_DB_PASSWORD
            value: toto
          - name: WORDPRESS_DB_USER
            value: toto 
          - name: WORDPRESS_DB_NAME
            value: wordpress
        ports:
          - containerPort: 80
        volumeMounts:
          - name: wordpress-data          
            mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        hostPath:
          path: /data/wordpress-volume
          type: DirectoryOrCreate
