kind: Pod
apiVersion: v1
metadata:
  name: mysql-pv
spec:
  containers:
  - name: mysql
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_USER
        value: test
      - name: MYSQL_DATABASE
        value: khidma
      - name: MYSQL_PASSWORD
        value: test
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: pvc
