kind: Pod
apiVersion: v1
metadata:
  name: mysql-volume
spec:
  containers:
  - name: mysql
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_USER
        value: test
      - name: MYSQL_DATABASE
        value: khidma
      - name: MYSQL_PASSWORD
        value: test
    ports:
      - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: volume
  volumes:
  - name: volume
    hostPath:
      path: /data
      type: Directory
